before:
  hooks:
    - go mod download
builds:
- id: github-weekly-report
  main: ./cmd
  binary: github-weekly-report
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
archives:
  - builds:
      - github-weekly-report
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: tar.gz
    files:
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
