name: github-weekly-report

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: go mod tidy run
      run: go mod tidy && git diff --no-patch --exit-code
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    - name: Build with Goreleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --snapshot --skip-publish --skip-validating --rm-dist
